### ISSUE TITLE
TODO from meeting on 5/28/2024

### ISSUE THREAD

**Issue by tashrifbillah** [pnlbwh/diskusage-logging#12]
- [x] Move Colin's files to his own folder
- [x] Upload Colin's code to his personal GitHub and submit a pull request to this GitHub
- [x] Add percentage labels on pie chart
- [x] Remove labels and strings off pies that are <10 %
- [x] At the bottom of the html report, have hyperlinked granularity of folders of the biggest 5 parent folders
- [x] After a hyperlink is clicked, move focus to the rendered table so the user do not wonder about if anything has happened (optional, can leave if too hard)
- [x] Tashrif will fix mailreport.sh
- [x] Remove the HH:mm timestamp from wherever needed in the html report (must remove `:SS` from all timestamps)
- [x] Next day, Colin will demo how his program works when there are multiple dirs in `_config/dirs.txt`
- [x] Add a variable month/year to look from, default should be last 12 months
- [x] Follow color scheme of `report-20231224.html` as reference
- [x] Change to only month/day such as 5/18 - 5/25:
  > 1 Week Changes for /data/pnl/ (2024-05-18 - 2024-05-25)
- [x] Round all GB sizes to two decimal points only

cc @colinjennings @RyanZurrin

**Comment by tashrifbillah** [comment]
Done
